# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/Gatsby.gitlab-ci.yml

image: node:14

variables:
  CI: ""

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - yarn
    - PUBLIC_URL=/layout yarn build
    - rm -rf public
    - mv build/ public/
    - ls -la public
  environment:
    name: pages
    url: https://kibernetiki.bws-gitlab.pp.ua/layout/
  artifacts:
    paths:
      - public/
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
